//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.08 at 08:04:19 AM CEST
//
/*******************************************************************************
 *
 * The authorship of this code and the accompanying materials is held by medshare GmbH, Switzerland.
 * All rights reserved. http://medshare.net
 *
 * Project Team: https://sourceforge.net/p/ehealthconnector/wiki/Team/
 *
 * This code is are made available under the terms of the Eclipse Public License v1.0.
 *
 * Accompanying materials are made available under the terms of the Creative Commons
 * Attribution-ShareAlike 4.0 License.
 *
 * Year of publication: 2015
 *
 *******************************************************************************/

package org.ehealth_connector.validation.service.config.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ApplicationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="downloads-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jquery-theme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="document-schema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationType", propOrder = { "downloadsUrl", "theme", "documentSchema",
		"pdfLevel", "pdfReportingLevel", "licenseKey" })
public class ApplicationType {

	@XmlElement(name = "downloads-url")
	protected String downloadsUrl;
	@XmlElement(name = "jquery-theme")
	protected String theme;
	@XmlElement(name = "document-schema")
	protected String documentSchema;
	@XmlElement(name = "pdf-level")
	protected String pdfLevel;
	@XmlElement(name = "pdf-reporting-level")
	protected String pdfReportingLevel;
	@XmlElement(name = "license-key")
	protected String licenseKey;

	/**
	 * Gets the value of the documentSchema property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDocumentSchema() {
		return documentSchema;
	}

	/**
	 * Gets the value of the downloadsUrl property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDownloadsUrl() {
		return downloadsUrl;
	}

	public String getLicenseKey() {
		return licenseKey;
	}

	public String getPdfLevel() {
		return pdfLevel;
	}

	public String getPdfReportingLevel() {
		return pdfReportingLevel;
	}

	/**
	 * Gets the value of the theme property (JQuery Theme).
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * Sets the value of the documentSchema property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDocumentSchema(String value) {
		this.documentSchema = value;
	}

	/**
	 * Sets the value of the downloadsUrl property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDownloadsUrl(String value) {
		this.downloadsUrl = value;
	}

	public void setLicenseKey(String licenseKey) {
		this.licenseKey = licenseKey;
	}

	public void setPdfLevel(String pdfLevel) {
		this.pdfLevel = pdfLevel;
	}

	public void setPdfReportingLevel(String pdfReportingLevel) {
		this.pdfReportingLevel = pdfReportingLevel;
	}

	/**
	 * Sets the value of the theme property (JQuery Theme).
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTheme(String value) {
		this.theme = value;
	}

}
