//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 09:35:50 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.oclc.org/dsdl/svrl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ehealth_connector.validation.service.schematron.bind;
