
################################################
# Primitive Datatypes
################################################


################################################
# Composite Datatypes
################################################
address.dataType=Address
address.narrative=classpath:narrative/AddressDt.html

humanname.dataType=HumanName
humanname.narrative=classpath:narrative/HumanNameDt.html

################################################
# Resources
################################################


#organization.class=ca.uhn.fhir.model.dstu.resource.Organization

patient.resourceType=Patient
patient.narrative=classpath:ca/uhn/fhir/narrative/Patient.html

organization.resourceType=Organization
organization.narrative=classpath:narrative/Organization.html

practitioner.resourceType=Practitioner
practitioner.narrative=classpath:narrative/Practitioner.html

practitionerrole.resourceType=PractitionerRole
practitionerrole.narrative=classpath:narrative/PractitionerRole.html

immunization.resourceType=Immunization
immunization.narrative=classpath:narrative/Immunization.html

immunizationrecommedation.resourceType=ImmunizationRecommendation
immunizationrecommedation.narrative=classpath:narrative/ImmunizationRecommendation.html

allergyintolerance.resourceType=AllergyIntolerance
allergyintolerance.narrative=classpath:narrative/AllergyIntolerance.html

condition.resourceType=Condition
condition.narrative=classpath:narrative/Condition.html

observation.resourceType=Observation
observation.narrative=classpath:narrative/Observation.html

composition.resourceType=Composition
composition.narrative=classpath:narrative/Composition.html

#reference.resourceType=Reference
#reference.class=org.hl7.fhir.r4.model.Reference
#reference.narrative=classpath:narrative/Reference.html
