/*
 * 
 * The authorship of this project and accompanying materials is held by medshare GmbH, Switzerland.
 * All rights reserved. https://medshare.net
 * 
 * Source code, documentation and other resources have been contributed by various people.
 * Project Team: https://sourceforge.net/p/ehealthconnector/wiki/Team/
 * For exact developer information, please refer to the commit history of the forge.
 * 
 * This code is made available under the terms of the Eclipse Public License v1.0.
 * 
 * Accompanying materials are made available under the terms of the Creative Commons
 * Attribution-ShareAlike 4.0 License.
 * 
 * This line is intended for UTF-8 encoding checks, do not modify/delete: äöüéè
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.04.08 at 10:09:10 AM CEST
//

package org.ehealth_connector.validation.service.schematron.bind;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.ehealth_connector.validation.service.schematron.RuleSet;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.oclc.org/dsdl/svrl}text" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.oclc.org/dsdl/svrl}ns-prefix-in-attribute-values" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{http://purl.oclc.org/dsdl/svrl}active-pattern" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;sequence maxOccurs="unbounded">
 *             &lt;element ref="{http://purl.oclc.org/dsdl/svrl}fired-rule" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *               &lt;element ref="{http://purl.oclc.org/dsdl/svrl}failed-assert"/>
 *               &lt;element ref="{http://purl.oclc.org/dsdl/svrl}successful-report"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="phase" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="schemaVersion" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "text", "nsPrefixInAttributeValues",
		"activePatternAndFiredRuleAndFailedAssert" })
@XmlRootElement(name = "schematron-output")
public class SchematronOutput {

	protected List<Text> text;
	@XmlElement(name = "ns-prefix-in-attribute-values")
	protected List<NsPrefixInAttributeValues> nsPrefixInAttributeValues;
	@XmlElements({ @XmlElement(name = "active-pattern", type = ActivePattern.class),
			@XmlElement(name = "fired-rule", type = FiredRule.class),
			@XmlElement(name = "failed-assert", type = FailedAssert.class),
			@XmlElement(name = "successful-report", type = SuccessfulReport.class) })
	protected List<Object> activePatternAndFiredRuleAndFailedAssert;
	@XmlAttribute(name = "title")
	@XmlSchemaType(name = "anySimpleType")
	protected String title;
	@XmlAttribute(name = "phase")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String phase;
	@XmlAttribute(name = "schemaVersion")
	@XmlSchemaType(name = "anySimpleType")
	protected String schemaVersion;

	@XmlTransient
	private RuleSet ruleSet = null;

	@XmlTransient
	private File sourceFile = null;

	/**
	 * Gets the value of the activePatternAndFiredRuleAndFailedAssert property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the activePatternAndFiredRuleAndFailedAssert
	 * property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows: <pre>
	 *    getActivePatternAndFiredRuleAndFailedAssert().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ActivePattern } {@link FiredRule } {@link FailedAssert }
	 * {@link SuccessfulReport }
	 *
	 *
	 */
	public List<Object> getActivePatternAndFiredRuleAndFailedAssert() {
		if (activePatternAndFiredRuleAndFailedAssert == null) {
			activePatternAndFiredRuleAndFailedAssert = new ArrayList<Object>();
		}
		return this.activePatternAndFiredRuleAndFailedAssert;
	}

	/**
	 * Gets the value of the nsPrefixInAttributeValues property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the nsPrefixInAttributeValues property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows: <pre>
	 *    getNsPrefixInAttributeValues().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link NsPrefixInAttributeValues }
	 *
	 *
	 */
	public List<NsPrefixInAttributeValues> getNsPrefixInAttributeValues() {
		if (nsPrefixInAttributeValues == null) {
			nsPrefixInAttributeValues = new ArrayList<NsPrefixInAttributeValues>();
		}
		return this.nsPrefixInAttributeValues;
	}

	/**
	 * Gets the value of the phase property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPhase() {
		return phase;
	}

	/**
	 * Returns the RuleSet that was used for the current validation
	 *
	 * @return RuleSet that was used for the current validation
	 */
	public RuleSet getRuleSet() {
		return ruleSet;
	}

	/**
	 * Gets the value of the schemaVersion property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSchemaVersion() {
		return schemaVersion;
	}

	/**
	 * Returns the Source File that was used for the current validation
	 *
	 * @return Source File that was used for the current validation
	 */
	public File getSourceFile() {
		return sourceFile;
	}

	/**
	 * Gets the value of the text property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the text property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows: <pre>
	 *    getText().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Text }
	 *
	 *
	 */
	public List<Text> getText() {
		if (text == null) {
			text = new ArrayList<Text>();
		}
		return this.text;
	}

	/**
	 * Gets the value of the title property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the phase property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPhase(String value) {
		this.phase = value;
	}

	/**
	 * Sets the RuleSet that was used for the current validation
	 *
	 * @param ruleSet
	 *            RuleSet that was used for the current validation
	 */
	public void setRuleSet(RuleSet ruleSet) {
		this.ruleSet = ruleSet;
	}

	/**
	 * Sets the value of the schemaVersion property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSchemaVersion(String value) {
		this.schemaVersion = value;
	}

	/**
	 * Sets the Source File that was used for the current validation
	 *
	 * @param sourceFile
	 *            Source File that was used for the current validation
	 */
	public void setSourceFile(File sourceFile) {
		this.sourceFile = sourceFile;
	}

	/**
	 * Sets the value of the title property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTitle(String value) {
		this.title = value;
	}

}
