//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.08 at 08:04:19 AM CEST
//
/*******************************************************************************
 *
 * The authorship of this code and the accompanying materials is held by medshare GmbH, Switzerland.
 * All rights reserved. http://medshare.net
 *
 * Project Team: https://sourceforge.net/p/ehealthconnector/wiki/Team/
 *
 * This code is are made available under the terms of the Eclipse Public License v1.0.
 *
 * Accompanying materials are made available under the terms of the Creative Commons
 * Attribution-ShareAlike 4.0 License.
 *
 * Year of publication: 2015
 *
 *******************************************************************************/

package ehealth_connector.validation.service.config.bind;

import java.io.File;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import ehealth_connector.validation.service.config.ConfigurationException;

/**
 * <p>
 * Java class for ConfigurationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="application" type="{}ApplicationType"/>
 *         &lt;element name="schematron" type="{}SchematronType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="baseDir" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationType", propOrder = { "application", "schematron" })
public class ConfigurationType {

	@XmlElement(required = true)
	protected ApplicationType application;
	@XmlElement(required = true)
	protected SchematronType schematron;
	@XmlAttribute
	@XmlSchemaType(name = "anySimpleType")
	protected String baseDir;

	/**
	 * Gets the value of the application property.
	 *
	 * @return possible object is {@link ApplicationType }
	 *
	 */
	public ApplicationType getApplication() {
		return application;
	}

	/**
	 * Gets the value of the baseDir property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public File getBaseDir() {
		if (baseDir == null)
			baseDir = new File(System.getProperty("catalina.base")).getAbsolutePath();
		return new File(baseDir).getAbsoluteFile();
	}

	/**
	 * Gets the value of the schematron property.
	 *
	 * @return possible object is {@link SchematronType }
	 *
	 */
	public SchematronType getSchematron() {
		return schematron;
	}

	/**
	 * Gets the value of the userDir property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public File getUserDir() {
		return new File(System.getProperty("user.dir")).getAbsoluteFile();
	}

	/**
	 * Returns the application's work directory. This is the directory, where
	 * the transformed rule-sets (the <cite>Schematron Validator</cite> files)
	 * and the archived rule-sets (the .zip file) are placed.
	 *
	 * @return the application's work directory.
	 */
	public File getWorkDir() throws ConfigurationException {
		File workDir = new File(getBaseDir() + "/work");
		if (!workDir.isDirectory()) {
			if (!workDir.mkdir()) {
				throw new ConfigurationException(
						String.format("Could not create working directory: '%s'", workDir));
			}
		}
		if (!workDir.canWrite()) {
			throw new ConfigurationException("Working directory is not writable");
		}
		return workDir.getAbsoluteFile();
	}

	/**
	 * Sets the value of the application property.
	 *
	 * @param value
	 *            allowed object is {@link ApplicationType }
	 *
	 */
	public void setApplication(ApplicationType value) {
		this.application = value;
	}

	/**
	 * Sets the value of the baseDir property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setBaseDir(String value) {
		this.baseDir = value;
	}

	/**
	 * Sets the value of the schematron property.
	 *
	 * @param value
	 *            allowed object is {@link SchematronType }
	 *
	 */
	public void setSchematron(SchematronType value) {
		this.schematron = value;
	}

}
