<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.projecthusky.fhir</groupId>
		<artifactId>husky-fhir</artifactId>
		<version>3.4.1-SNAPSHOT</version>
	</parent>
	<groupId>org.projecthusky.fhir.validation</groupId>
	<artifactId>husky-fhir-validation</artifactId>


	<dependencies>

		<dependency>
			<!-- The Checker Framework enhances Java's type system to make it
			more powerful and useful. -->
			<groupId>org.checkerframework</groupId>
			<artifactId>checker-qual</artifactId> <!-- MIT -->
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-structures-r4</artifactId>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-validation-resources-r4</artifactId>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-caching-caffeine</artifactId>
			<version>${hapi.fhir.version}</version>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-server</artifactId>
		</dependency>

		<!-- Tests (EPL 2.0) -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<!--<version>1.5.18</version>-->
			<scope>test</scope>
		</dependency>
    </dependencies>
</project>